### ISSUE TITLE
Redirect docs directory to index.html

### ISSUE THREAD

**Issue by amanshu** [geocento/SEDAS-issues#1]
Currently browsing to https://geobrowsertest.satapps.org/docs returns a 403 forbidden page.  It would be better to set up a redirect to send anyone accessing it to https://geobrowsertest.satapps.org/docs/index.html instead.

**Comment by raul-geocento** [comment]
Has been corrected and deployed in testing environment https://geobrowsertest.satapps.org/docs/

**Comment by amanshu** [comment]
Awesome!
