### ISSUE TITLE
GET request only accepts single id

### ISSUE THREAD

**Issue by amanshu** [geocento/SEDAS-issues#11]
Running a GET request request with more than one id returns returns a 404.
I've tried:
https://geobrowsertest.satapps.org/api/request?ids=1527%2C1528%2C1529%2C1525%2C1526
and:
https://geobrowsertest.satapps.org/api/request?ids=1527,1528,1529,1525,1526

**Comment by amanshu** [comment]
As a workaround for now, it might be worth updating the documentation to say it's only possible to check one request at a time?

**Comment by raul-geocento** [comment]
Has been fixed in version 0.23
