### ISSUE TITLE
with missing XML we get a server error in the response code

### ISSUE THREAD

**Issue by dittytwo** [geocento/SEDAS-issues#12]
posting some missing XML (an example below) 
<sensors>
<start>${startSearch}</start>
<stop>${stopSearch}</stop>
<aoiWKT>POLYGON(${polygon})</aoiWKT>
<filters>
${minCoveragePercent}
${maxCloudPercent}
${opticalProductType}
${polarisation}
${sarProductType}
${orbitDirection}
</filters>
</sensors>

We get a invalid response of
{"errorCode":400,"errorMessage":"Instantiation of [simple type, class com.geocento.webapps.sedas.extapi.server.domain.ProductFilters] value failed: HTTP 500 Internal Server Error"}

**Comment by raul-geocento** [comment]
I do not understand very well the problem... could you tell the API call you are trying and what are you sending as parameter?

**Comment by dittytwo** [comment]
sorry we are POST to https://geobrowsertest.satapps.org/api/search

an example of the POST data:
<sensors>
    <sensorFilters>
    </sensorFilters>
    <start>2017-08-07T00:00:29Z</start>
    <stop>2017-08-31T15:27:27Z</stop>
    <aoiWKT>POLYGON((1 36, 27 36, 27 59, 1 59, 1 36))</aoiWKT>
    <filters>
    		<minCoveragePercent>0</minCoveragePercent>
	    	<maxCloudPercent>0</maxCloudPercent>
		<opticalProductType>L1C</opticalProductType>
	 	<polarisation>HV</polarisation>
    		<sarProductType>ALL</sarProductType>
		<orbitDirection>DESCENDING</orbitDirection>
    </filters>
</sensors>

we then get the error mentioned above. this is a different to the expected outcome of a code 200 and no products returned which would be the same for the json if sent the same missing elements.

**Comment by raul-geocento** [comment]
I have been testing this and the error is thrown by the server before reaching our code. I think there is not much we can do about this, the user should provide all the fields in the XML objects. I have been taking a look at the jersey/jackson documentation but I have not seen anything to fix this.

**Comment by amanshu** [comment]
I think the fact that it's throwing a different error to the JSON is probably OK - it's doing different checks and rejecting the XML as malformed early.  I'm more concerned that the errorCode is 400, when the errorMessage says it's 500!

**Comment by amanshu** [comment]
I'm still getting an errorCode of 400 with an errorMessage of 500 for the following:
<sensors>
    <sensorFilters>
        <type>All</type>
    </sensorFilters>
    <start>2017-09-10T23:37:19Z</start>
    <stop>2017-10-09T16:38:12Z</stop>
    <aoiWKT>POLYGON((82 74, 106 74, 106 90, 82 90, 82 74))</aoiWKT>
    <filters>
    </filters>
</sensors>

**Comment by amanshu** [comment]
I'm still getting a 400 error code and a 500 error message

**Comment by raul-geocento** [comment]
Problem creating sensorFilter or productFilter objects in search request. Jersey/Jackson was using "\n" caracter as content. This situation is handled now and the object is not being created in this case. 

Rather than returning a 400 or 500 error, now it is possible to send this request:

`<sensors>
    <sensorFilters>
    	
    	
    </sensorFilters>
    <start>2017-08-07T00:00:29Z</start>
    <stop>2017-08-31T15:27:27Z</stop>
    <aoiWKT>POLYGON((1 36, 27 36, 27 59, 1 59, 1 36))</aoiWKT>
    <filters>
    		<minCoveragePercent>0</minCoveragePercent>
	    	<maxCloudPercent>0</maxCloudPercent>
		<opticalProductType>L1C</opticalProductType>
	 	<polarisation>HV</polarisation>
    		<sarProductType>ALL</sarProductType>
		<orbitDirection>DESCENDING</orbitDirection>
    </filters>
</sensors>`

And the API does not return any error, it will not take into account the <sensorFilters> field which is a better behaviour

**Comment by dittytwo** [comment]
this has now been fixed and now errors are reported back to the user and data is provided.
