### ISSUE TITLE
XML requests returning JSON

### ISSUE THREAD

**Issue by amanshu** [geocento/SEDAS-issues#13]
Whenever we run an XML request, the response is in JSON.  The documentation appears to have XML responses, which would suggest it should be XML.

**Comment by raul-geocento** [comment]
To receive XML the "Accept":"application/xml" header should be included in the request headers

**Comment by amanshu** [comment]
I can't see that in the documentation anywhere.  Could you point me to it?  I'm thinking it probably needs to be on the main page as one of the first paragraphs.
