### ISSUE TITLE
XML requests returning JSON Error messages

### ISSUE THREAD

**Issue by amanshu** [geocento/SEDAS-issues#14]
Create a request with the "Content-Type" and "Accept" headers set to "application/xml".  The body of the search request should cause an error to be returned (i.e. a search request with no aoi).  The response will be in JSON rather than XML.

**Comment by raul-geocento** [comment]
Is this for me?

**Comment by raul-geocento** [comment]
Sorry, I was not understanding the issue correctly. It has been fixed.

**Comment by raul-geocento** [comment]
Has been fixed in version 0.23
