### ISSUE TITLE
test server thumbnail object gets redirected

### ISSUE THREAD

**Issue by dittytwo** [geocento/SEDAS-issues#15]
when testing and looking at the thumbnail in the products from posting this to https://geobrowsertest.satapps.org/api/search
``
 <searchRequest>
  <sensorFilters>
    <type>All</type>
  </sensorFilters>
  <start>2017-07-23T10:21:16Z</start>
  <stop>2017-08-15T00:53:45Z</stop>
  <aoiWKT>POLYGON((-102 68, -71 68, -71 61, -102 61, -102 68))</aoiWKT>
  <filters>
    <minCoveragePercent>0</minCoveragePercent>
    <maxCloudPercent>10</maxCloudPercent>
    <opticalProductType>L1C</opticalProductType>
    <polarisation>HH</polarisation>
    <sarProductType>OCN</sarProductType>
    <orbitDirection>ASCENDING</orbitDirection>
  </filters>
</searchRequest>
``

An example of the URL returned under thumbnail for the above product search:
https://sedasdmtest.satapps.org/qls/qlmgr.php?sceneid=S2A/MSIL1C/2017/07/24/S2A_MSIL1C_20170724T175911_N0205_R041_T14VNQ_20170724T175913/abb4aa0266ba22b5774bcc739457407e/geo-quick-look-thumb.png

when opened this gets redirected to this URL

https://geobrowsertest.satapps.org/archiveql/aewebpub/small.png

is this as expected on the test system.

**Comment by GGlanfield** [comment]
Yes. There are a few hundred thousand scenes from the database that were copied from PROD to TESTING as to test query speeds etc - but the actual full res imagery and quicklooks etc were not copied over to TESTING (only the database metadata was copied). This is why the majority of searches in the TESTING env geobrowser will say no image when running a query. Once we are ok with query speeds etc the test data can be removed.
