### ISSUE TITLE
HTTP Request pop out links not working in documentation

### ISSUE THREAD

**Issue by amanshu** [geocento/SEDAS-issues#16]
Every HTTP Request definition in the documentation has a new window icon next to it that looks like this: 
![link](https://user-images.githubusercontent.com/12099689/31182485-e3708262-a91b-11e7-8020-58beef5d832f.png)

Unfortunately none of them work.

**Comment by raul-geocento** [comment]
Enunciate configuration changed to avoid empty link

**Comment by dittytwo** [comment]
I have just tested this and this is still an issue
