### ISSUE TITLE
Some examples still showing confusing data

### ISSUE THREAD

**Issue by amanshu** [geocento/SEDAS-issues#2]
https://geobrowsertest.satapps.org/docs/json_Instrument.html:
- the second minAngle/maxAngle are still 12345.0

https://geobrowsertest.satapps.org/docs/json_Satellite.html: 
- Except for the first one, the minAngle/maxAngel are still 12345.0.  
- The final resolution is 12345.0

**Comment by raul-geocento** [comment]
Has been corrected and deployed in testing environment. It seems to be a bug with enunciate an arrays. It has been forced to use only one element.
