### ISSUE TITLE
Clicking Run Search without selecting an AoI hides the warning message

### ISSUE THREAD

**Issue by amanshu** [geocento/SEDAS-issues#20]
Log onto SEDAS and hover the mouse over the 'RUN SEARCH' button.  A tooltip will be displayed saying 'Please define an Area of Interest first.'  If you click on the RUN SEARCH button, this tooltip disappears.  There is now no notification of why you can't search.

It would be better to have a clear pop-up error message displayed saying you need to select an Area of Interest first.

**Comment by raul-geocento** [comment]
Completed (already done before in git commit 6ae6d4e)
