### ISSUE TITLE
Type place name search is intermittent

### ISSUE THREAD

**Issue by amanshu** [geocento/SEDAS-issues#21]
Sorry to start off with, but this will be an annoying one.

A number of times while attempting to search for places today it's been unable to find anything.  There was a five minute period where it couldn't find France.  It doesn't seem consistent.  Generally you just have to delete a few characters and retype and it will work again, but sometimes it just doesn't seem to find somewhere.

**Comment by raul-geocento** [comment]
I have assigned it to milestone 0.25 to track it anyway but I have been testing it and it works perfectly.

**Comment by amanshu** [comment]
Told you it would be annoying.  If it's just a one off issue then we'll close it at 0.25.

**Comment by raul-geocento** [comment]
This widget is using the google geolocator service... Maybe you have tested it in a moment the service was not working well... I will test it from time to time anyway

**Comment by amanshu** [comment]
Not seen again.  Closing as a one off.
