### ISSUE TITLE
Editing Rectangles when scrolled out behaves strangely

### ISSUE THREAD

**Issue by amanshu** [geocento/SEDAS-issues#22]
Create a short wide Rectangle that covers Antarctica.  Zoom out so you can see two copies of the Rectangle.  Select one of the corners of the rectangle to go into edit mode.  Now slowly drag the world sideways.  As the Rectangle moves from one field of vision to the other you reach a stage where two of the corners are editable on one rectangle and two are editable on another.  It would be better if this moved with the location marker.

**Comment by raul-geocento** [comment]
Could you send some screenshots? I do not understand very well the behaviour

**Comment by amanshu** [comment]
![screenshot-2017-11-16 sedas](https://user-images.githubusercontent.com/12099689/32887185-e69303f0-caba-11e7-9e87-b193a4c66c55.png)
Here's a pretty good example.  As you can see I'm editing one rectangle, but because of the zoom it shows up on two different rectangles.

**Comment by raul-geocento** [comment]
Corrected for version 0.27

**Comment by amanshu** [comment]
It's still not perfect, but it's such a strange edge case that I'm happy to accept it until we get really bored.
