### ISSUE TITLE
Searched AoI tooltips inconsistent (and wrong)

### ISSUE THREAD

**Issue by amanshu** [geocento/SEDAS-issues#27]
Create a rectangle AoI and run a search.  Hover the mouse over the AoI and a tooltip of "AoI: 'Custom circle AoI'" appears.  This is wrong.

Create a circle AoI and run a search.  Hover the mouse over the AoI and no tooltip appears.  Please add it.

Create a polygon AoI and run a search.  Hover the mouse over the AoI and a tooltip of "AoI: 'Custom polygon AoI'" appears.  This is good.  We like this one.

**Comment by raul-geocento** [comment]
Fixed for version 0.25

**Comment by dittytwo** [comment]
This now fails search as you can great massive areas it also doesn't work when zoomed out as the map wraps and point appear on different sides of the map

**Comment by raul-geocento** [comment]
I do not understand very well, but this seems to be a diffrent issue... isn't it?

**Comment by dittytwo** [comment]
Raul yes please ignore me

**Comment by raul-geocento** [comment]
Sure ;)
