### ISSUE TITLE
Allow API to filter searches by Satellite Name or Group

### ISSUE THREAD

**Issue by amanshu** [geocento/SEDAS-issues#28]
Currrently it is not possible to filter an API search by Satellite Group or Satellite Name.  You can effectively limit the search to a Satellite Group by specifying a particular Sensor Type, but it would be nice to be able to explicitly filter by Satellite Name or Group

**Comment by amanshu** [comment]
Raul/Graham can you confirm whether this is achievable or not?

**Comment by raul-geocento** [comment]
Yes Cameron, it is achievable

**Comment by raul-geocento** [comment]
Hi Cameron:

As the satellite/source group is configurable via admin panel, to complete this issue, a new API end point has to be developed. Something similar to getSatellites that we already have but for satellite groups and their related satellites. So the user is able to list them and know what groups he can use for searching...

Let me know if you are OK with this.

**Comment by amanshu** [comment]
Seems good to me.

**Comment by raul-geocento** [comment]
This API change has been deployed for testing. A new endpoint has been developed to retrieve the current configured source groups and their satellites, doc here:

https://geobrowsertest.satapps.org/docs/resource_SensorResource.html

The search request object has been modified to add the two new parameters "sourceGroup" and "satelliteName", doc here:

https://geobrowsertest.satapps.org/docs/json_SearchRequest.html
