### ISSUE TITLE
Required fields marked as optional

### ISSUE THREAD

**Issue by amanshu** [geocento/SEDAS-issues#3]
https://geobrowsertest.satapps.org/docs/xml_ns0_credentials.html:
- The username and password fields have a 'min/max occurs' of 0/1.  This should be 1/1.

https://geobrowsertest.satapps.org/docs/xml_ns0_searchRequest.html:
- The aoiWKT, start and stop fields have a 'min/max occurs' of 0/1.  This should be 1/1.

**Comment by raul-geocento** [comment]
Corrected and deployed in testing.
