### ISSUE TITLE
FileSize and FileHash db update

### ISSUE THREAD

**Issue by GGlanfield** [geocento/SEDAS-issues#33]
Some attribute data on the product page, namely Filesize and FileHash are named filesize and filehash - these need to be updated.

**Comment by amanshu** [comment]
Graham are you looking at this, or is it a question for the Catapult?

**Comment by GGlanfield** [comment]
More of a reminder, it should be run at some point (but it isn't urgent)


________________________________

**Comment by dittytwo** [comment]
I need some clarification as to where this is in the product. 
and also is this just a lowercase to upper case change..

**Comment by GGlanfield** [comment]
I didn't answer your question properly (a couple back). This is a Geocento catalogue update. Mongodb is fine.

**Comment by GGlanfield** [comment]
Note to self - run the updates in batches VS all at once as to mitigate against the master/slave becoming out of sync

**Comment by GGlanfield** [comment]
Batch tested on TESTING env. Ready for PROD.

**Comment by amanshu** [comment]
@GGlanfield Did this make it into 0.2.6?
