### ISSUE TITLE
Product search not returning values

### ISSUE THREAD

**Issue by amanshu** [geocento/SEDAS-issues#41]
Run an api/search that returns values.  Select one of the results and extract the supplierId from it.  
Run api/search/products?ids=${supplierId}.

I would expect this to return a list of products, including the one from the original search.  All that appears to be being received is an empty list.

**Comment by raul-geocento** [comment]
It has been checked with the sample info on testing and it is working... Could you provide more information about this? Environment (Testing / Prod) Search parameters? Supplier id?

Thanks

**Comment by amanshu** [comment]
If you run the SearchProducts test from [this test set](https://satapps-my.sharepoint.com/personal/cameron_shiell_sa_catapult_org_uk/_layouts/15/guestaccess.aspx?docid=187d29e7d64414ef3ab88a155d0078b33&authkey=AWeiJVyrIyz9pFZb7cuBRbA&e=szA3X3) it creates a number of failures.

**Comment by amanshu** [comment]
It appears this is due to future acquisitions being returned with a different id being returned in that field.  Would be better to split the two fields into... two fields and add an acquisition boolean.

**Comment by amanshu** [comment]
This then becomes a duplicate of #47
