### ISSUE TITLE
download 404 error

### ISSUE THREAD

**Issue by dittytwo** [geocento/SEDAS-issues#42]
using the Search api on test OST https://geobrowsertest.satapps.org/api/search
POST data:
```
<sensors>
    <sensorFilters>
        <type>All</type>
    </sensorFilters>
    <start>2017-10-29T16:18:16Z</start>
    <stop>2017-11-28T16:18:16Z</stop>
    <aoiWKT>POLYGON((133 -37, 153 -37, 153 -5, 133 -5, 133 -37))</aoiWKT>
   	<filters>
	   	<minCoveragePercent>0</minCoveragePercent>
	   	<maxCloudPercent>100</maxCloudPercent>
		<opticalProductType>ALL</opticalProductType>
		<sarProductType>ALL</sarProductType>
		<orbitDirection>ALL</orbitDirection>
    	</filters>
</sensors>
```
with the above we take the first download url
"https://sedasdmtesting.satapps.org/datamgr/datamgr.php?sceneid=S2A_MSIL1C_20171030T005711_N0206_R002_T53JMJ_20171030T040510.zip"
and we get a 404 error message 
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /datamgr/datamgr.php was not found on this server.</p>
<hr>
<address>Apache/2.4.29 (Unix) Server at sedasdmtesting.satapps.org Port 80</address>
</body></html>
```

**Comment by raul-geocento** [comment]
This one is for Graham

**Comment by GGlanfield** [comment]
It is that certificate issue I believe - i.e when Fede asked why the thumbnails weren't loading on TESTING (the thumbnails come from the download manager as well).

Last I remember, is we asked CEMS to check the certificate on Fortigate.

**Comment by amanshu** [comment]
I thought you'd opened up your logs to debug level and were looking through them for more information?

**Comment by GGlanfield** [comment]
Just forwarded last email

**Comment by amanshu** [comment]
Trev to test and close if appropriate

**Comment by amanshu** [comment]
All working fine.
