### ISSUE TITLE
Terms of Use link not working

### ISSUE THREAD

**Issue by amanshu** [geocento/SEDAS-issues#45]
On the [sign up page](https://geobrowser.satapps.org/#register:undefined), the 'Terms of Use and Distribution for Sentinel data' link should point to http://sedas.satapps.org/data-uses-distribution/.  At the moment it points to nothing.

**Comment by raul-geocento** [comment]
This is a configuration issue, this value was set for production environment but not for testing. There is other link in this page is  working neither for production nor for testing...  "Terms of Use and Distribution for Sentinel data" What link should we use for this? Could you provide it?

**Comment by raul-geocento** [comment]
Done
