### ISSUE TITLE
Marketing check box missing from sign up form

### ISSUE THREAD

**Issue by amanshu** [geocento/SEDAS-issues#46]
According to the 'Your Rights' section on the [Privacy Policy](http://sedas.satapps.org/privacy-policy/):
"You have the right to ask us not to process your personal data for marketing purposes. ... You can exercise your right to prevent such processing by checking certain boxes on the forms we use to collect your data."

Currently there are no such check boxes.  I'll amend the webpage for now, but it would be preferable to include them and instead.

**Comment by amanshu** [comment]
The check box should state:
"‘I would like to receive opportunities and updates from the Satellite Applications Catapult."

**Comment by amanshu** [comment]
Check box should be available on Sign up, and visible in the Admin page for each user.
Add a settings page for each user so they can update their preferences

**Comment by raul-geocento** [comment]
Done, created a new "Settings" panel that should be good for adding other user settings in the future

**Comment by amanshu** [comment]
Yep, looks good.
