### ISSUE TITLE
Add AirSAR to the frontend

### ISSUE THREAD

**Issue by amanshu** [geocento/SEDAS-issues#48]

**Comment by dittytwo** [comment]
Hi guys we have Airsair data in the test frontend we get a server error when trying to add to the basket. is this as expected (see image attached
![error trying to download](https://user-images.githubusercontent.com/23172628/36255328-79c1e574-1246-11e8-9f4e-ff447a5024f7.JPG)

**Comment by raul-geocento** [comment]
Working on it

**Comment by raul-geocento** [comment]
I think it is working. Maybe you lost the session... this kind of things happen when the session is lost. Maybe we should view a way to handle the session.

**Comment by amanshu** [comment]
This has been delayed due to license issues.
