### ISSUE TITLE
Implement max no of queries per second - for email alerts

### ISSUE THREAD

**Issue by GGlanfield** [geocento/SEDAS-issues#51]
Currently the geobrowser checks the catalogue every few hours for new imagery (for email alerts). The number of queries it sends to the catalogue per second can be large, and when combined with GUI and/or API queries - can result in max query limits being reached. Can this be amended so that the Geobrowser 
sends a max of two queries per second, when checking for email alerts.

**Comment by raul-geocento** [comment]
Done

**Comment by amanshu** [comment]
Is there any real way for me to test this?  I guess I could raise some alerts and then bombard the servers?

**Comment by raul-geocento** [comment]
You can set some alerts for some users and check the logs... (admin panel) and search for this message
"Sending AE query from alert" check that the difference in time between this messages is at least 500 milliseconds
