### ISSUE TITLE
Adding to basket notification

### ISSUE THREAD

**Issue by GGlanfield** [geocento/SEDAS-issues#55]
When not logged in, and a user tries to add a scene to their basket, can the message of "You need to be signed in to add a product to your cart" be more obvious by being displayed over the cart (this is what happens if you try to add a product via the product page). Raul, this one needs the green light (or not) from catapult first.

**Comment by amanshu** [comment]
Ok, firstly lets grey out the cart icon if the user isn't logged in.  If there's a way to grey out the thumbnail as well that would be good.

I'd also consider adding a banner beneath each thumbnail saying "You need to be logged in to add product to your cart."  Something like:
![untitled](https://user-images.githubusercontent.com/12099689/36785860-4cef323c-1c7c-11e8-8acb-6eebfc9379e1.png)

**Comment by amanshu** [comment]
Is this something that could be done as part of 0.2.7?

**Comment by raul-geocento** [comment]
Yes, I think so

**Comment by raul-geocento** [comment]
It looks like this now, let me know if you like it

![image](https://user-images.githubusercontent.com/31733460/37912944-f183f87c-3113-11e8-8e73-0c46f325414a.png)

**Comment by amanshu** [comment]
Looks great!
