### ISSUE TITLE
Request status errors

### ISSUE THREAD

**Issue by amanshu** [geocento/SEDAS-issues#6]
I'm attempting to query the status of requests: 1302, 1303, 1306, 1309, 1310, 1312, 1315, 1316, 1317, 1318, 1322, 1326, 1327, 1328, 1329, 1332, 1333, 1337, 1343, 1349, 1358, 1362, 1364.
They are returning an error of "No enum constant com.geocento.webapps.sedas.common.share.domain.STATUS.started" and a code of 500.

**Comment by raul-geocento** [comment]
I could not reproduce this error, could you attach the jmeter file? I think it depends on the user that sends the request

**Comment by amanshu** [comment]
Run JSON_Requests.jmx to make sure there are requests in the system.  The run JSON_CheckExistingRequests.jmx to query them - you'll need to update the Looper start point so you cover the request range.  2001 is about right at time of writing.

You should see failed requests coming out.

**Comment by amanshu** [comment]
Hmmm... it does appear this has been fixed already.
