### ISSUE TITLE
Create limited user search history

### ISSUE THREAD

**Issue by amanshu** [geocento/SEDAS-issues#60]
Create a page that logs the last 25 (? for discussion) attempted downloads.
This should be populated regardless of whether the download is successful or not.
When a user attempts to download an item from the cart it should be automatically removed from the cart and added to the download history.

**Comment by GGlanfield** [comment]
Notes for discussion with Raul/Catapult.
* When a user clicks on the download button from their cart, that scene will be automatically removed from the cart.
* Currently a download is only logged if the user is logged in and the scene exists - therefore if there is an issue (such as the scene isn’t found) then it will not be included in the users history. This needs to be changed.
* The new download history, available from the cart, should include any downloads (gui and api). There maybe 1000's so don't return all scenes at once.  Start with the most recent 10 downloads, and then paginate.
* Have a "clear history" button.
* Think about how this will affect stats. We could have a new user of anonymous, and when someone clears their history, the user for those download records will get changed to anonymous.
* Think about how API calls and any LTA requests affects the above.

**Comment by amanshu** [comment]
This issue is being made smaller in scope with the excess being moved to new issues.
