### ISSUE TITLE
Automatically delete downloads from cart

### ISSUE THREAD

**Issue by amanshu** [geocento/SEDAS-issues#61]
When a user starts downloading a product from the shopping cart, remove the product from the cart and add it to the users history.

**Comment by raul-geocento** [comment]
Completed

**Comment by amanshu** [comment]
Hmmm... I just tried using the UK enabled data sets searching the UK for the last week.  All of the downloads themselves failed - I assume because they've been tidied up our end - but the downloads didn't appear in the download list.

**Comment by amanshu** [comment]
Yep, works now :)
