### ISSUE TITLE
New db attribute for Geobrowser

### ISSUE THREAD

**Issue by GGlanfield** [geocento/SEDAS-issues#64]
Add account created date attribute for new users (if it does not already exist). Add column to stats csv that can be downloaded from admin panel. This is required for UKSA/ESA reporting.

**Comment by raul-geocento** [comment]
Registered date exists but is empty, need to chack why

**Comment by raul-geocento** [comment]
Now it is used when a user signs up and also is avaible in admin panel user list and in the CSV export

**Comment by amanshu** [comment]
Awaiting Admin Rights to check.

**Comment by raul-geocento** [comment]
Login as admin / sedas (this is only for testing environment)
