### ISSUE TITLE
Improve debug when emails fail

### ISSUE THREAD

**Issue by GGlanfield** [geocento/SEDAS-issues#66]
Specifically for any user related emails (signup etc).

**Comment by amanshu** [comment]
I'm assuming I'm not going to be able to test this?  It's internal to you guys?

**Comment by raul-geocento** [comment]
Yes it something internal. Deb told us last week that an user has problem to sign up beacuse he did not received the sign up email. Everything seemed to be fine so we have detailed a bit more the logs about mail sending. I think it is not necessary to be tested
