### ISSUE TITLE
Automate user sign up

### ISSUE THREAD

**Issue by amanshu** [geocento/SEDAS-issues#68]
Can we update the sign up so that:
1) A user fills out a signup form.
2) A confirmation email is automatically sent.
3) The user clicks a link in the email to verify they're account.

This will also require expanding the signup form to capture some more information - I'll check that and get back to you.

**Comment by raul-geocento** [comment]
What I propose for this is:

- Add only the obligatory fields of the second step to the first sign up step
- Include the rest of information in the new settings panel (now only for the marketing check). So the user can change it when he likes

**Comment by amanshu** [comment]
Agreed, so during the first sign up step you'll be asked for:
Username, Email, First Name, Last Name(s), Organisation, Country, Utilisation domain, Usage Field, Password, Confirm Password and reCaptcha.
They'll also agree to the SeDAS Terms and Conditions and the Terms of Use and Distribution for Sentinel data and be asked to confirm we can email them.
They will then receive a confirmation email and accepting that will complete sign up and give them access to SeDAS.
We'll entirely skip the approval process.
On the settings panel the user will be able to access and change:
First name, Last Name(s), Organisation, Country, Utilisation Domain and Usage Field

**Comment by raul-geocento** [comment]
Completed
